version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.9
      docker: 18
    commands:
      - pip install flask
  build:
    commands:
      - echo Logging into Amazon ECR...
      - aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 211125401262.dkr.ecr.us-east-1.amazonaws.com
      - echo Building Docker image...
      - docker build -t azmi-finaltest .
      - docker tag azmi-finaltest 211125401262.dkr.ecr.us-east-1.amazonaws.com/azmi-finaltest
      - docker push 211125401262.dkr.ecr.us-east-1.amazonaws.com/azmi-finaltest
artifacts:
  files: "**/*"
